spring:
  cloud:
    nacos:
      discovery:
        namespace: e2562b25-c730-42ff-ace1-fa3a5fed5fbb
        server-addr: 10.100.20.243:8848
  application:
    name: oauth-center
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    main:
      allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev_root
    password: D0tC3^v_LYw$24LY
    url: jdbc:mysql://10.100.20.243:3306/pim?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ${oauth.base.client-id}
            client-secret: ${oauth.base.secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/sso/login
        provider:
          custom:
            authorization-uri: ${oauth.base.url}/auth/realms/${oauth.base.reaml}/protocol/openid-connect/auth
            token-uri: ${oauth.base.url}/auth/realms/${oauth.base.reaml}/protocol/openid-connect/token
            user-info-uri: ${oauth.base.url}/auth/realms/${oauth.base.reaml}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:${oauth.base.url}/auth/realms/${oauth.base.reaml}/protocol/openid-connect/certs}
          issuer-uri: ${oauth.base.url}/auth/realms/${oauth.base.reaml}

auth2:
  keycloak:
    client-id: ${oauth.base.client-id}
    client-secret: ${oauth.base.secret}
    token-uri: ${oauth.base.url}/auth/realms/${oauth.base.reaml}/protocol/openid-connect/token

server:
  port: 8081

resourceServer:
    resourceId: ${oauth.base.client-id}

keycloak:
  auth-server-url: ${oauth.base.url}/auth
  realm: ${oauth.base.reaml}
  #public-client: true
  resource: ${oauth.base.client-id}
  principal-attribute: preferred_username
  credentials:
    secret: ${oauth.base.secret}
oauth:
  base:
    url: https://sha-keycloak.etocrm.net
    secret: ec35ce77-fb0b-405e-8254-fbedcb1eee70
    client-id: oauth-center
    reaml: myrealm

logging:
  level:
    com.etocrm: error