spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/keycloak1
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: client-one
            client-secret: dc769165-2a2e-40c2-bcba-13abd511fecf
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/sso/login
        provider:
          custom:
            authorization-uri: http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/certs}
          issuer-uri: http://localhost:8080/auth/realms/sso-demo
  thymeleaf:
    cache: false
  cache:
    type: NONE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  main:
    allow-bean-definition-overriding: true
auth2:
  keycloak:
    client-id: client-one
    client-secret: dc769165-2a2e-40c2-bcba-13abd511fecf
    token-uri: http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/token

server:
  port: 8081
  servlet:
    context-path: /client-one

logging:
  level:
    org.springframework: DEBUG
resourceServer:
    resourceId: client-one




keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: sso-demo
  #public-client: true
  resource: client-one
  principal-attribute: preferred_username
  credentials:
    secret: dc769165-2a2e-40c2-bcba-13abd511fecf
