spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: sso-client-1
            client-secret: 5b195950-b7d0-410c-a879-2fed5b9fae64
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/client-one/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/auth/realms/sso-demo/protocol/openid-connect/certs}
  thymeleaf:
    cache: false
  cache:
    type: NONE

server:
  port: 8082
  servlet:
    context-path: /client-one

logging:
  level:
    org.springframework: DEBUG